site_name: Hive 函数
site_url: https://hive-functions.leovan.tech
site_author: Leo Van | 范叶亮
site_description: Hive 函数

# Repository
repo_name: leovan/cytoscape-functions
repo_url: https://github.com/leovan/hive-functions
edit_uri: edit/main/docs/

# Copyright
copyright: 版权所有 &copy; 2001-2021, Leo Van

# Google analytics
google_analytics:
  - G-CC3LZ8TS82
  - auto

# Navigation
nav:
  - 主页: index.md
  - JSON 函数: json-functions.md

# Theme
theme:
  name: material
  custom_dir: theme
  include_search_page: false
  search_index_only: true
  language: zh
  features:
    - tabs
    - navigation.expand
    - search.suggest
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/hive-functions-icon.png
  logo: images/hive-functions-icon.png

# Plugins
plugins:
  - search:
      lang: en

# Extra
extra:
  social:
    - icon: material/home
      link: https://leovan.me
      name: 个人主页
    - icon: material/github
      link: https://github.com/leovan
      name: Github
extra_css:
  - css/image.css
  - css/table.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/math.js

# Markdown extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: leovan
      repo: hive-functions
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde